-- DropForeignKey
ALTER TABLE "Comment" DROP CONSTRAINT "Comment_postId_fkey";

-- AlterTable
ALTER TABLE "Comment" ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "editDate" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Meme" ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "editDate" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "joinDate" SET DATA TYPE TIMESTAMPTZ;

-- AddForeignKey
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Meme"("postId") ON DELETE CASCADE ON UPDATE CASCADE;
